# This file was generated by GoReleaser. DO NOT EDIT.
cask "fpl-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/dmallory42/fpl-cli/releases/download/v#{version}/fpl-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "b6720e86409ba1b5575863798fb5c8d803eef13a35209daadcfba54ec8bf671c"
    end
    on_arm do
      url "https://github.com/dmallory42/fpl-cli/releases/download/v#{version}/fpl-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "d1f5769ae6643e9c403f5af467347e225403d04b16513860490389e9869da07e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmallory42/fpl-cli/releases/download/v#{version}/fpl-cli_#{version}_linux_amd64.tar.gz"
      sha256 "de451f6c0833f0f06598929d7dce560bee0c9eb71a9ac0f2f1f69e9daceccce9"
    end
    on_arm do
      url "https://github.com/dmallory42/fpl-cli/releases/download/v#{version}/fpl-cli_#{version}_linux_arm64.tar.gz"
      sha256 "31ff3e6f52611c9de3048469a80c4bcce22c01cda192841413bcda4e29af4f18"
    end
  end

  name "fpl-cli"
  desc "A fast, scriptable CLI for the public Fantasy Premier League API"
  homepage "https://github.com/dmallory42/fpl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fpl-cli"

  # No zap stanza required

end
