# This file was generated by GoReleaser. DO NOT EDIT.
cask "fpl-cli" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/dmallory42/fpl-cli/releases/download/v#{version}/fpl-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "624005b8cb7c3d72fc22a98698f3af8a3dc93e07e6cea80b03b3fc89e686daee"
    end
    on_arm do
      url "https://github.com/dmallory42/fpl-cli/releases/download/v#{version}/fpl-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "31f1cd39b514518f91f31ccf5f02c9697db5b46c63e190fa02e258b2eba89748"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmallory42/fpl-cli/releases/download/v#{version}/fpl-cli_#{version}_linux_amd64.tar.gz"
      sha256 "b33d2e42e653664604a4e407f3093a9910fdf5e6081a74503eceb1fe96786048"
    end
    on_arm do
      url "https://github.com/dmallory42/fpl-cli/releases/download/v#{version}/fpl-cli_#{version}_linux_arm64.tar.gz"
      sha256 "a64d4a61bf7c240067a33f1d38603418d8513f204ce72a2ac0491909d1b29ce6"
    end
  end

  name "fpl-cli"
  desc "A fast, scriptable CLI for the public Fantasy Premier League API"
  homepage "https://github.com/dmallory42/fpl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fpl-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fpl-cli"]
    end
  end

  # No zap stanza required

end
